---
title: "ZIBR random effect"
author: "Eric Z Chen"
date: "January 4, 2015"
output: 
  html_document: 
    number_sections: yes
    theme: cosmo
    toc: yes
---



```{r setup, include=FALSE}
####### install necessary packages
packages <- c(#'knitr',
              'foreach','doParallel',
              'metakit',
              'pheatmap','reshape2',
              'ggplot2','tidyr','dplyr')
for (pk in packages){
  if (!require(pk,character.only = TRUE)){
    if(pk=='pheatmap'){
      devtools::install_github("raivokolde/pheatmap")
    } 
    else if (pk=='metakit'){
      devtools::install_github("chvlyl/metakit")
    }
    else{
      install.packages(pk,dep=TRUE,repos="http://cran.us.r-project.org")
    }
  }
  require(pk,character.only = TRUE,quietly=TRUE)
}

#########################
### change the working directory
try(setwd('3_Analysis/'))
try(dir.create("temp"))

#####################################################
#### load the package instead of sourcing the code in the future  
########################################################
####
source('../1_Package/ZIBRE/R/zibre.R')
source('../1_Package/ZIBRE/R/fit_beta_regression_random_effect.R')
source('../1_Package/ZIBRE/R/fit_logistic_regression_random_effect.R')
source('../1_Package/ZIBRE/R/fit_zero_inflated_beta_regression_random_effect.R')
source('../1_Package/ZIBRE/R/generate_gaussian_quad_points.R')
source('../1_Package/ZIBRE/R/simulate_zero_inflated_beta_data.R')


####################################################
#opts_chunk$set(#fig.path = '~/3_Results/',
#  root.dir = '../3_Results/',
#  progress = TRUE, verbose = TRUE,
#  warning=FALSE, message=FALSE,echo=TRUE)
```  


```{r note,inclue=FALSE, eval=FALSE}
only fit beta

antiTNF vs. EEN
```


```{r function}
list_to_vector = function(est){
  if(length(est) == 3) {
    res.vec <- c(as.vector(est$est.table),
                 est$s2.est,
                 est$v.est)
    names(res.vec) <- c(paste('beta',rownames(est$est.table),'coef',sep='.'),
                        paste('beta',rownames(est$est.table),'pval',sep='.'),
                        'beta.s2','beta.v')
  }
  if(length(est) == 6){
    res.vec <- c(as.vector(as.vector(est$logistic.est.table)),
                 as.vector(est$beta.est.table),
                 est$logistic.s1.est,
                 est$beta.s2.est,
                 est$beta.v.est,
                 est$overall.test.p)
    names(res.vec) <- c(paste('logistic',
                              rownames(est$logistic.est.table),'coef',sep='.'),
                        paste('logistic',
                            rownames(est$logistic.est.table),'pval',sep='.'),
                        paste('beta',rownames(est$beta.est.table),'coef',sep='.'),
                        paste('beta',rownames(est$beta.est.table),'pval',sep='.'),
                        'logistic.s1',
                        'beta.s2','beta.v','overall.p')
  }
  return(res.vec)
}

`%+%` = function(x,y){
  paste(x,y,sep='')
}
```


## Simulation


### Parameter estimation: beta random effect
```{r simulation_beta, cache=TRUE}
sim.N <- 100
sub.N <- c(20,50,100,200)
time.N <- c(5)
#sub.N <- 100
#time.N <- 5
beta.true <- as.matrix(c(-0.5,0.5))
s2.true <- 0.8
v.true <- 5
est.avg.list <- list()
est.var.list <- list()
for (subject.n in sub.N){
  for (time.n in time.N){
    cat('Subject ',subject.n,' Time ', time.n, '\n')
    est.list <- list()
    ###############################
    ### try parallel computing here
    for (sim.n in 1:sim.N){
      cat("Sim ",sim.n,'\n')
      ptm <- proc.time()
      sim <- simulate_beta_random_effect_data(
                  subject.n=subject.n,time.n=time.n,
                  Z=as.matrix(c(rep(0,subject.n/2*time.n),rep(1,subject.n/2*time.n))),
                  ##beta
                  beta=beta.true,
                  s2=s2.true,
                  v=v.true,
                  sim.seed=sim.n)
      v.init <- sim$v
      s2.init <- sim$s2
      Z.coeff.init <- sim$beta
      Z <- sim$Z
      Y <- sim$Y
      subject.ind <- sim$subject.ind
      time.ind  <- sim$time.ind
      Y <- as.matrix(Y)
      Z <- as.matrix(Z)
      #library(profr)
      #p <- profr(fit_beta_random_effect(Z=Z,Y=Y,
      #             subject.ind=subject.ind,
      #             time.ind=time.ind,
      #             quad.n=50,verbose=FALSE)
      #)
      #plot(p)
      est <- fit_beta_random_effect(Z=Z,Y=Y,
                   subject.ind=subject.ind,
                   time.ind=time.ind,
                   quad.n=50,verbose=FALSE)
      est.list[[paste('sim',sim.n,sep='')]] <- list_to_vector(est)
      
      ####
      #beta.data <- data.frame(Y=Y,Z=Z)
      #beta.model <- betareg(Y~var1,data=beta.data)
      #print(summary(beta.model))
      #print(est)
      #break
    }
    est.mat <- t(as.data.frame(est.list))
    est.avg.list[[paste('subject',subject.n,'time', time.n,sep='')]] <- apply(est.mat,2,mean,na.rm=TRUE)
    est.var.list[[paste('subject',subject.n,'time', time.n,sep='')]] <- apply(est.mat,2,sd,na.rm=TRUE)
    #break
  }
  #break
}
est.avg.mat <- t(as.data.frame(est.avg.list))
est.var.mat <- t(as.data.frame(est.var.list))
write.csv(data.frame(mean=est.avg.mat[,-c(3,4)],sd=est.var.mat[,-c(3,4)]),
           ## remove the average pval
          file=paste('../4_Results/Simulation_Parameter_Estimation_Beta_b_neg05_05_s2_08_v_5.csv',sep=''))
```


### Parameter estimation: zero-inflated beta random effect
```{r simulation_zibr, cache=TRUE}
#ptm <- proc.time()
sim.N <- 1000
sub.N <- c(20,50,100,200)
time.N <- c(5)
#sub.N <- 200
#time.N <- 5
alpha.true <- as.matrix(c(-0.5,1))
beta.true <- as.matrix(c(-0.5,0.5))
s1.true <- 1
s2.true <- 0.8
v.true <- 5
est.avg.list <- list()
est.var.list <- list()
for (subject.n in sub.N){
  for (time.n in time.N){
    cat('Subject ',subject.n,' Time ', time.n, '\n')
    est.list <- list()
    ###############################
    ### try parallel computing here
    for (sim.n in 1:sim.N){
      cat("Sim ",sim.n,'\n')
      sim <- simulate_zero_inflated_beta_random_effect_data(
                  subject.n=subject.n,time.n=time.n,
                  X=as.matrix(c(rep(0,subject.n/2*time.n),rep(1,subject.n/2*time.n))),
                  ##logistic
                  alpha=alpha.true,
                  ##beta
                  beta=beta.true,
                  s1=s1.true,s2=s2.true,
                  v=v.true,
                  sim.seed=sim.n)
      v.init <- sim$v
      s1.init <- sim$s1
      s2.init <- sim$s2
      X.coeff.init <- sim$alpha
      Z.coeff.init <- sim$beta
      X <- sim$X
      Z <- sim$Z
      Y <- sim$Y
      subject.ind <- sim$subject.ind
      time.ind  <- sim$time.ind
      X <- as.matrix(X)
      Y <- as.matrix(Y)
      Z <- as.matrix(Z)
      
      est <- zibre(logistic.cov=X,beta.cov=Z,Y=Y,
                   subject.ind=subject.ind,
                   time.ind=time.ind,
                   quad.n=30,verbose=TRUE)
      
      est.list[[paste('sim',sim.n,sep='')]] <- list_to_vector(est)
      
      ####
      #beta.data <- data.frame(Y=Y,X=X)
      #beta.data <- beta.data[Y>0,]
      #beta.model <- betareg(Y~var1,data=beta.data)
      #print(summary(beta.model))
      #print(est)
      #break
    }
    est.mat <- t(as.data.frame(est.list))
    est.avg.list[[paste('subject',subject.n,'time', time.n,sep='')]] <- apply(est.mat,2,mean)
    est.var.list[[paste('subject',subject.n,'time', time.n,sep='')]] <- apply(est.mat,2,sd)
    #break
  }
  #break
}
est.avg.mat <- t(as.data.frame(est.avg.list))
est.var.mat <- t(as.data.frame(est.var.list))
#write.csv(data.frame(mean=est.avg.mat[,-c(3,4,7,8,12)],sd=est.var.mat[,-c(3,4,7,8,12)]),
           ## remove the average pval
#          file=paste('../4_Results/Simulation_Parameter_Estimation_Logistic_Beta_a_neg05_1_b_neg05_05_s1_1_s2_08_v_5.csv',sep=''))
#proc.time() - ptm
```




### Type I error: zero-inflated beta random effect
```{r simulation_type_1_error, cache=TRUE}
##############################
####sim.list$true.par
####sim.list$sim.data
####sim.list$zibr
sim.list <- list()

##############################
##### generate true parameters
sim.list$true.par <- list()
sim.N <- 10000
subject.n <- 100
time.n <- 5
alpha <- as.matrix(c(0.5,0))
beta <- as.matrix(c(0.5,0))
s1 <- 0.1
s2 <- 0.1
v <- 5

X=as.matrix(c(rep(0,subject.n/2*time.n),rep(1,subject.n/2*time.n)))
for (sim.n in 1:sim.N){
  sim.list$true.par[["sim"%+%sim.n]] <- list(subject.n=subject.n, time.n=time.n,
                     alpha=alpha, beta=beta,
                     s1=s1, s2=s2,v=v,
                     X=X,sim.seed=sim.n)
}

#############################
### generate simulation data
sim.list$sim.data <- list()
sim.list$sim.data <- lapply(sim.list$true.par,function(true.p){do.call(simulate_zero_inflated_beta_random_effect_data,true.p)})

#############################
### run models on simulated data
run_zibre = function(X=X,Y=Y,Z=Z,
                   subject.ind=subject.ind,
                   time.ind=time.ind,...){
  est <- zibre(logistic.cov=X,beta.cov=Z,Y=Y,
                   subject.ind=subject.ind,
                   time.ind=time.ind,
                   quad.n=30,verbose=TRUE)
  return(list(logistic.p=est$logistic.est.table[[2,2]],beta.p=est$beta.est.table[[2,2]],overall.p=est$overall.test.p))
}


####################################
#### check if the previous simulation results already exist
run.parallel <- TRUE
sim.list$zibr <- list()
sim.temp.file <- "temp/Simulation_Data_Type_I_Error.rds"
#### load previous simulation results
if (file.exists(sim.temp.file)) {
  print("exist")
  sim.list.temp <- readRDS(sim.temp.file)
  ##### check if the simulation data are identical
  #### if zibr already exists, use the previous results
  if (exists("zibr",where=sim.list.temp) & 
      identical(sim.list.temp$sim.data, sim.list$sim.data, ignore.environment = TRUE) &
      (length(sim.list.temp$zibr) == length(sim.list.temp$sim.data))
      ) {
    sim.list$zibr <- sim.list.temp$zibr
  #### otherwise, run zibr
  }else{
      if (run.parallel) {
        sim.list$zibr <- mclapply(sim.list$sim.data,
                                  function(sdata) {
                                    do.call(run_zibre,sdata);
                                  },mc.cores = 5)
      }else{
        sim.list$zibr <- lapply(sim.list$sim.data,
                                function(sdata) {
                                  do.call(run_zibre,sdata);
                                })
      }
    }
} else{
  if (run.parallel) {
    sim.list$zibr <- mclapply(sim.list$sim.data,
                              function(sdata) {
                                do.call(run_zibre,sdata);
                              },mc.cores = 5)
  }else{
    sim.list$zibr <- lapply(sim.list$sim.data,
                            function(sdata) {
                              do.call(run_zibre,sdata);
                            })
  }
saveRDS(sim.list, "temp/Simulation_Data_Type_I_Error.rds")



###################################
### evaluate the simulation results
#melt(sim.list$zibr) %>% 
##spread(L2,value) %>%
#ggplot(aes(x = value)) + geom_histogram(binwidth = 0.1) + facet_grid( ~ L2) 

melt(sim.list$zibr) %>% 
#spread(L2,value) %>%
group_by(L2) %>%
summarize(error=sum(value<0.05)/length(unique(L1)))
```



## Real data analysis

### Load real data
```{r load_data,cache=TRUE}
##############################################
##### Load MetaPhlAn results
TLevel <- 'G'
### Only need the PLEASE data
PLEASE.file <- paste('../0_Data/MetaPhlAn/PLEASE/',TLevel,
            '_Remove_unclassfied_Renormalized_Merge_Rel_MetaPhlAn_Result.xls',sep='')
PLEASE.raw <- read.table(PLEASE.file,sep='\t',header=TRUE,row.names = 1,
                         check.names=FALSE,stringsAsFactors=FALSE)
PLEASE.raw <- t(PLEASE.raw)
cat('samples','taxa',dim(PLEASE.raw),'\n')
PLEASE.raw[1:3,1:3]

taxa.raw <- PLEASE.raw
  
###################################
### load total non-human read counts
human.read.file <- '../0_Data/Human_Reads/please_combo_human_reads.xls'
human.read <- read.table(human.read.file,sep='\t',header=TRUE,
                         row.names=1,stringsAsFactors=FALSE)

############################
### Filter low depth samples
low.depth.samples <- subset(human.read,NonHumanReads<10000)
low.depth.samples[,1:5]

### Delete these samples from PLEASE data.
### Due to the low sequencing depth, some of the samples have no MetaPhlAn output
### These are the samples with MetaPhlAn output but also low sequencing
rownames(taxa.raw)[which(rownames(taxa.raw) %in% rownames(low.depth.samples))]
### Before deletion
dim(taxa.raw)
### After deletion
taxa.raw <- taxa.raw[-which(rownames(taxa.raw) %in% rownames(low.depth.samples)),]
dim(taxa.raw)

####################################
### Filter low abundant bacterial data
filter.index1 <- apply(taxa.raw,2,function(X){sum(X>0)>0.4*length(X)})
filter.index2 <- apply(taxa.raw,2,function(X){quantile(X,0.9)>1})
taxa.filter <- taxa.raw[,filter.index1 & filter.index2]
taxa.filter <- 100*sweep(taxa.filter, 1, rowSums(taxa.filter), FUN="/")
cat('after filter:','samples','taxa',dim(taxa.filter),'\n')
cat(colnames(taxa.filter),'\n')
head(rowSums(taxa.filter))

####
taxa.data <- taxa.filter
dim(taxa.data)

###########################
#### Load sample information
sample.info.file <- '../0_Data/Sample_Information/2015_02_13_Processed_Sample_Information.csv'
sample.info <- read.csv(sample.info.file,row.names=1)


rm(PLEASE.file)
rm(PLEASE.raw)
rm(human.read.file)
rm(filter.index1)
rm(filter.index2)
rm(sample.info.file)
```


### Fit ZIBR on real data: time and response in antiTNF
```{r fit_zibrre_time_response_in_antitnf}

######
## Code time as weeks or days, instead of 1,2,3,4

######
reg.cov <-
data.frame(Sample=rownames(taxa.data),stringsAsFactors = FALSE) %>% 
left_join(add_rownames(sample.info,var = 'Sample'),by='Sample')%>%
dplyr::filter(!is.na(Response)) %>%
dplyr::select(Sample,Time,Subject,Response) %>%
group_by(Subject) %>% summarise(count = n()) %>% dplyr::filter(count==4) %>%
dplyr::select(Subject) %>%
left_join(add_rownames(sample.info,var = 'Sample'),by='Subject') %>%
mutate(Response=ifelse(Response=='Response',1,0)) %>%
mutate(Time=ifelse(Time=='1',0,ifelse(Time=='2',1,ifelse(Time=='3',4,ifelse(Time=='4',8,NA))))) %>% 
dplyr::filter(Treatment.Specific=='antiTNF') %>%
dplyr::select(Sample,Subject,Time,Response) %>%
dplyr::mutate(Time.X.Response=Time*Response)


######
X <- as.matrix(reg.cov[,c('Time','Response','Time.X.Response')])
#colnames(X) <- c('Time','Response')
rownames(X) <- reg.cov$Sample
Z <- X
subject.ind <- reg.cov$Subject
time.ind   <- reg.cov$Time
taxa.data.fit  <- taxa.data[reg.cov$Sample,]

###############

spe.all <- colnames(taxa.data.fit)
p.species.list <- list()


for (spe in spe.all){
  spe <- 'g__Escherichia'
  cat(spe,'\n')
  Y <- taxa.data.fit[,spe,drop=F]/100
  cat('Zeros/All',sum(Y==0),'/',length(Y),'\n')
  if (sum(Y>0)<10 | sum(Y==0) <10 | max(Y)<0.01){
    print('skip')
    next
  }else{
    est <- zibre(logistic.cov=X,beta.cov=Z,Y=Y,
                 subject.ind=subject.ind,
                 time.ind=time.ind,
                 quad.n=30,verbose=TRUE)
    p.species.list[[spe]] <- list_to_vector(est)
#     p.species[spe,c(3,1,4,2)] <- as.vector(est$logistic.est.table[-1,])
#     p.species[spe,c(8,6,9,7)] <- as.vector(est$beta.est.table[-1,])
#     p.species[spe,5]  <-  est$logistic.s1.est
#     p.species[spe,10] <- est$beta.s2.est
#     p.species[spe,11] <- est$beta.v.est
#     p.species[spe,12] <- est$overall.test.p
  }
  break
}
p.species <- t(as.data.frame(p.species.list))
####
write.csv(signif(p.species[,-grep('intersept',colnames(p.species))],3),file=paste('../4_Results/Real_Data_Estimation_Results_antiTNF_Time_Response_Interaction.csv',sep=''))

####################
#### Boxplot
for (spe in spe.all){
  #spe <- 'g__Escherichia'
  abu <- taxa.data.fit[,spe,drop=FALSE]
  colnames(abu) <- 'Taxa'
  ### presence
  p<-add_rownames(as.data.frame(abu),var='Sample') %>% 
  right_join(reg.cov,by='Sample') %>% 
  dplyr::select(Taxa,Response,Time) %>%
  mutate(Response=ifelse(Response==1,'Response','Non.Response')) %>%
  group_by(Response,Time) %>%
  summarize(Present=sum(Taxa>0)/length(Taxa)) %>%
  ggplot(aes(x=factor(Time),fill=factor(Response),y=Present)) + geom_bar(position="dodge",stat="identity")+
  ggtitle(spe)
  plot(p)
  ### non-zero abundance
  p<-add_rownames(as.data.frame(abu),var='Sample') %>% 
  right_join(reg.cov,by='Sample') %>% 
  dplyr::select(Taxa,Response,Time) %>%
  mutate(Response=ifelse(Response==1,'Response','Non.Response')) %>%
  dplyr::filter(Taxa>0) %>%
  ggplot(aes(factor(Time),log(Taxa/(100-Taxa)),fill=Response))+
  geom_boxplot() + 
  ggtitle(spe)
  plot(p)
}
```


### Fit ZIBR on real data: antiTNF vs. EEN
```{r fit_zibrre_treatment}
#### create covariates, 
#### Time, antiTNF+EEN
reg.cov <-
data.frame(Sample=rownames(taxa.data),stringsAsFactors = FALSE) %>% 
left_join(add_rownames(sample.info,var = 'Sample'),by='Sample')%>%
dplyr::filter(Treatment.Specific!='PEN') %>%
dplyr::select(Sample,Time,Subject,Response,Treatment.Specific) %>%
group_by(Subject) %>% summarise(count = n()) %>% dplyr::filter(count==4) %>%
dplyr::select(Subject) %>%
left_join(add_rownames(sample.info,var = 'Sample'),by='Subject') %>%
mutate(Treat=ifelse(Treatment.Specific=='antiTNF',1,0)) %>%
dplyr::select(Sample,Subject,Time,Response,Treat) %>%
dplyr::mutate(Time=ifelse(Time=='1',0,ifelse(Time=='2',1,ifelse(Time=='3',4,ifelse(Time=='4',8,NA))))) %>%
dplyr::mutate(Time.X.Treatment=Time*Treat) %>%
as.data.frame
### take out first time point
reg.cov.t1   <-  subset(reg.cov,Time==0)
reg.cov.t234 <-  subset(reg.cov,Time!=0)

###############
spe.all <- colnames(taxa.data.fit)
p.species.list <- list()

for (spe in spe.all){
  ###### create covariates
  X <- data.frame(reg.cov.t234[,c('Time','Treat','Time.X.Treatment')],
                 Baseline=taxa.data[reg.cov.t1$Sample, spe]/100)
  rownames(X) <- reg.cov.t234$Sample
  Z <- X
  subject.ind <- reg.cov.t234$Subject
  time.ind   <- reg.cov.t234$Time
  ####
  #spe <- 'g__Escherichia'
  cat(spe,'\n')
  Y <- taxa.data[reg.cov.t234$Sample, spe]/100
  cat('Zeros/All',sum(Y==0),'/',length(Y),'\n')
  if (sum(Y>0)<10 | sum(Y==0) <10 | max(Y)<0.01){
    print('skip')
    next
  }else{
    est <- zibre(logistic.cov=X,beta.cov=Z,Y=Y,
                 subject.ind=subject.ind,
                 time.ind=time.ind,
                 quad.n=30,verbose=TRUE)
    p.species.list[[spe]] <- list_to_vector(est)
  }
  #break
}

####
p.species <- t(as.data.frame(p.species.list))
####
write.csv(signif(p.species[,-grep('intersept',colnames(p.species))],3),file=paste('../4_Results/Real_Data_Estimation_Results_Treatment_antiTNF_EEN.csv',sep=''))

# ####################
# #### Boxplot
for (spe in spe.all){
  #spe <- 'g__Streptococcus'
  #spe <- "g__Bacteroides" 
  ####
  p<- data.frame(reg.cov.t234,
                 Baseline=taxa.data[reg.cov.t1$Sample, spe],
                 Taxa=taxa.data[reg.cov.t234$Sample, spe]) %>%
  dplyr::mutate(Treatment=ifelse(Treat==1,"anitTNF","EEN")) %>%
  dplyr::select(Subject, Time, Treatment, Taxa) %>%
  ggplot(aes(factor(Time),Taxa,fill=factor(Treatment)))+  
  geom_boxplot() + 
  #geom_point() + stat_smooth(method=loess) +
  #stat_summary(aes(group=Treatment), fun.y=median, geom="line", colour="green") +
  #geom_jitter() +
  #coord_cartesian(ylim=c(0,10)) +
    #ylim(c(0,5)) + 
  ggtitle(spe)
  plot(p)
  
}
```

### Fit ZIBR on real data: logFCP
```{r fit_zibrre_logfcp}
#### create covariates, 
#### Time, logFCP
reg.cov <-
data.frame(Sample=rownames(taxa.data),stringsAsFactors = FALSE) %>% 
left_join(add_rownames(sample.info,var = 'Sample'),by='Sample')%>%
dplyr::filter(!is.na(FCP)) %>%
dplyr::select(Sample,Time,Subject,Response,log.FCP) %>%
group_by(Subject) %>% summarise(count = n()) %>% dplyr::filter(count==4) %>%
dplyr::select(Subject) %>%
left_join(add_rownames(sample.info,var = 'Sample'),by='Subject') %>%
#mutate(Treat=ifelse(Treatment.Specific=='antiTNF',1,0)) %>%
dplyr::select(Sample,Subject,Time,Response,log.FCP) %>%
dplyr::mutate(Time=ifelse(Time=='1',0,ifelse(Time=='2',1,ifelse(Time=='3',4,ifelse(Time=='4',8,NA))))) %>%
#dplyr::mutate(Time.X.Treatment=Time*Treat) %>%
as.data.frame
### take out first time point
reg.cov.t1   <-  subset(reg.cov,Time==0)
reg.cov.t234 <-  subset(reg.cov,Time!=0)

###############
spe.all <- colnames(taxa.data.fit)
p.species.list <- list()

for (spe in spe.all){
  ###### create covariates
  X <- data.frame(reg.cov.t234[,c('Time','log.FCP')],
                 Baseline=taxa.data[reg.cov.t1$Sample, spe]/100)
  rownames(X) <- reg.cov.t234$Sample
  Z <- X
  subject.ind <- reg.cov.t234$Subject
  time.ind   <- reg.cov.t234$Time
  ####
  #spe <- 'g__Escherichia'
  cat(spe,'\n')
  Y <- taxa.data[reg.cov.t234$Sample, spe]/100
  cat('Zeros/All',sum(Y==0),'/',length(Y),'\n')
  if (sum(Y>0)<10 | sum(Y==0) <10 | max(Y)<0.01){
    print('skip')
    next
  }else{
    est <- zibre(logistic.cov=X,beta.cov=Z,Y=Y,
                 subject.ind=subject.ind,
                 time.ind=time.ind,
                 quad.n=30,verbose=TRUE)
    p.species.list[[spe]] <- list_to_vector(est)
  }
  #break
}

####
p.species <- t(as.data.frame(p.species.list))
####
write.csv(signif(p.species[,-grep('intersept',colnames(p.species))],3),file=paste('../4_Results/Real_Data_Estimation_Results_logFCP.csv',sep=''))

# ####################
# #### Boxplot
for (spe in spe.all){
  #spe <- 'g__Streptococcus'
  spe <- "g__Parabacteroides"
  spe <- "g__Alistipes"
  ####
  p<- data.frame(reg.cov.t234,
                 Baseline=taxa.data[reg.cov.t1$Sample, spe],
                 Taxa=taxa.data[reg.cov.t234$Sample, spe]) %>%
  #dplyr::mutate(Treatment=ifelse(Treat==1,"anitTNF","EEN")) %>%
  #dplyr::select(Subject, Time, Treatment, Taxa) %>%
  ggplot(aes(log.FCP,Taxa,color=factor(Time)))+ geom_point() + 
  #stat_summary(aes(group=Treatment), fun.y=mean, geom="line", colour="green") +
  #geom_jitter() +
  #coord_cartesian(ylim=c(0,2)) +
    #ylim(c(0,5)) + 
  ggtitle(spe)
  plot(p)
  
}
```



